### ISSUE TITLE
verilog_utils.vh is missing

### ISSUE THREAD

**Issue by kulp** [olofk/wb_intercon#1]
The header `verilog_utils.vh` is included in many rtl files, but is apparently not in the git repository.

I think it is required at least for `ff1` in `wb_mux.v`.

**Comment by olofk** [comment]
Hi,

You can find this file here https://github.com/openrisc/orpsoc-cores/blob/master/cores/verilog_utils/verilog_utils.vh

If you are using FuseSoC it will automatically pick up the dependeny on verilog_utils. I should probably add a note where to find it for people who are not using FuseSoC

Hope this helps

//Olof

**Comment by kulp** [comment]
Thanks. I ended up writing a function that looked just like that once I figured out what it means.
